language: node_js
node_js:
- 0.10.x
deploy:
  provider: heroku
  api_key:
    secure: it4uAGWv2+40omoUGUVgJdSDMVFbwz38lLCPSmws/5jv3OwGQc6jnSvrEIkf27UessHuPpkptJSpprbnEz/ZPWCG4vCj7LeGirUPc3qu+ZW4wMkLAKOx08JenesWvgo+RfPbFnRroD9qNyU8GhF8gW4+PjquSaVxBM1G7CCuxWA=
  app: volary-pigeon-staging
  strategy: git
  on:
    repo: VolaryFoundation/Pigeon
notifications:
  email:
    recipients:
    - nick@volary.org
    - lorne@volary.org
    - brendan@volary.org
    - michael@volary.org
    on_success: change
    on_failure: always
